### ISSUE TITLE
Ability to submit search without JS

### ISSUE THREAD

**Issue by lionkmp** [PontusHorn/Pico-Search#1]
Hello!

Search is a great addition to Pico, thank you! This improved my site greatly.

Can you please make it possible that search form is submitted without JavaScript? A simple GET request would be best (so that the page can be still forwarded to friends), and usually the search term is in "q=" query parameter.

**Comment by PontusHorn** [comment]
Hello, and thanks for raising the issue. Definitely a valid concern! Expect a fix shortly. :)

**Comment by PontusHorn** [comment]
Updated the code and README.md with a fix. The changes you have to make on your side, aside from updating the plugin file, is amending the search form. You need an `action="/search"` attribute on the `<form>` (adjust path if necessary), and a `name="q"` attribute on the input text field.

When you submit the form without JavaScript intercepting the submission, you will be directed to something like "/search?q=foobar", which then redirects you to "/search/foobar".

**Comment by lionkmp** [comment]
Hi, thank you, it works great!

When I search for "text/plain" (or anything with a "/") I get error 404. But I think this problem is not caused by this fix.

**Comment by PontusHorn** [comment]
Glad it worked. I believe the issue you're having with slashes is due to running Apache with `AllowEncodedSlashes` set to `Off` (this is the default setting). If you set `AllowEncodedSlashes NoDecode` in your `httpd.conf` (see [this SO answer](http://stackoverflow.com/a/9933890/4850778) for details), I think it should work better.

If it doesn't, feel free to open another issue about it. :)
