### ISSUE TITLE
Search Template or CSS not loaded

### ISSUE THREAD

**Issue by ghost** [PontusHorn/Pico-Search#4]
Hello Developer,

I would love to use the search plugin and have it installed. Unfortunately CSS is not shown under http://picocms.wpzweinull.ch/sub/search.

What could be the problem?

I've already renamed search.html to search.twig. Unfortunately without success.

I recently noticed this at the Pico blog. The same thing that CSS is not displayed.

I use the last Pico CMS version.

Maybe you can help me and look at it.

Thanks in advance.

**Comment by PontusHorn** [comment]
It looks like you need a `sub/search.md` in your content folder. It needs to be there to prevent the 404 page, and to make sure the correct template is used. I've edited the installation instructions to hopefully make the necessary steps a bit clearer.

Let me know if that works for you.

**Comment by ghost** [comment]
Unfortunately no success at http://picocms.wpzweinull.ch/sub/search and CSS is not loaded. I have it as I said it made and in the directory `/sub` the search.md created.

I also use the Default Pico Theme and still seems to be something that does not work.

**Comment by PontusHorn** [comment]
Ah, it looks very different now from when I last looked at it. Your problem is probably that your template *only* contains the example code from the instructions. It is only meant to show how that specific part of the page might look. The template will also need all the things going on around the search results, which will depend completely on your page.

If you simply want to make your search results page look like your standard page, but with search results, I'd suggest editing your `templates/default/index.html` and change `{{ content }}` into `{% block content %} {{ content }} {% endblock %}`.

That enables you to extend this base template and reuse everything it has going on in your `templates/default/search.twig` like this:
```twig
{% extends "index.twig" %}

{% block content %}
    {{ parent() }}
    <!-- SEARCH RESULT CODE HERE -->
{% endblock content %}
```

**Comment by ghost** [comment]
Thank you! Your current instructions have helped me very much and now the search page is also displayed. Then it is so that the themes, which one can install, still have to be edited and supplemented. That's good to know.

You can now close this issue.

**Comment by PontusHorn** [comment]
No worries, glad you got it to work! :)
